# Generated by Django 6.1.1 on 2026-09-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('nombre', models.CharField(max_length=15)),
                ('rut', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('motivo_visita', models.CharField(max_length=320)),
                ('hora_entrada_salida', models.TimeField(verbose_name='Selecciona la hora')),
            ],
        ),
    ]
