# Generated by Django 6.1.1 on 2026-09-08 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caso1_visitas', '0003_visita_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(70000000), django.core.validators.MaxValueValidator(259999999)]),
        ),
    ]
