# Generated by Django 6.1.1 on 2026-09-08 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caso1_visitas', '0004_alter_visita_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='hora_salida',
        ),
        migrations.AlterField(
            model_name='visita',
            name='hora_entrada',
            field=models.TimeField(default=datetime.time(1, 29, 59, 352277)),
        ),
    ]
