# Generated by Django 6.1.1 on 2026-09-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caso1_visitas', '0005_remove_visita_hora_salida_alter_visita_hora_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='hora_entrada',
            field=models.DateTimeField(),
        ),
    ]
