# Generated by Django 6.1.1 on 2026-09-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caso1_visitas', '0005_remove_visita_hora_salida_alter_visita_hora_entrada'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        ALTER TABLE "caso1_visitas_visita"
                        ALTER COLUMN "hora_entrada" TYPE timestamp with time zone
                        USING (
                            (CURRENT_DATE + "hora_entrada") AT TIME ZONE 'UTC'
                        )
                    ''',
                    reverse_sql='''
                        ALTER TABLE "caso1_visitas_visita"
                        ALTER COLUMN "hora_entrada" TYPE time without time zone
                        USING (
                            ("hora_entrada" AT TIME ZONE 'UTC')::time
                        )
                    ''',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='visita',
                    name='hora_entrada',
                    field=models.DateTimeField(),
                ),
            ],
        ),
    ]
